### ISSUE TITLE
polymer data-binding not rendering as html ?

### ISSUE THREAD

**Issue by Stefdv** [EPA-WG/embed-page#4]
Is it possible to let `htmlContent` be 'rendered' as html? ( instead of showing `<h1>In Iframe</h1>` )

```
<dom-module>
   <template>
      <embed-page>[[htmlContent]]</embed-page>
   </template>
   <script>
       class TestPage extends Polymer.element { 
           ....
          static get properties() {
              return {
                  htmlContent: {
                         type:String,
                         value: '<h1>In Iframe</h1>'
                    }
              }
          } 
       }
....
</script>
```

**Comment by sashafirsov** [comment]
Direct embedding of HTML into `<embed-page>` like `<embed-page><h1>H1 content</h1></embed-page>` works fine, but binding seems broken. Looking into.

**Comment by sashafirsov** [comment]
@Stefdv , please check out v0.0.6 release, it has Polymer binding sample. 
Due to limitation of HTML sanitizing in template, the binding is provided via 'html' attribute. 
See the live sample on [embed-page/demo/inline-content.html](https://raw-dot-custom-elements.appspot.com/EPA-WG/embed-page/v0.0.6/embed-page/demo/inline-content.html)

Does it work for you?

**Comment by Stefdv** [comment]
Great :)  Thank you. 
closing.
