### ISSUE TITLE
Awesome Implementation for Web Components Area

### ISSUE THREAD

**Issue by edwardchanjw** [EPA-WG/embed-page#7]
Hi, This project seem to be the first true modular movement in Web Components.
I been look into way to jailing JavaScript but had yet found any solution that seem promising. This look great for next generation lightweight web component module that is embedded without iframe.

If Google doesn't yet pulling resources to this working group since they also working on Google Caja, which seem to be few that at least certain promising, I am recommend you can refer or pulling collaboration from [Lightning System Aura Locker Services](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/security_code.htm) or its implementation [Open Source Aura Framework](https://github.com/forcedotcom/aura/)

Sorry just bump in your project and giving a shout out. Feel free to close this issue, and get it out of your way. Thanks for the project initiative.

**Comment by sashafirsov** [comment]
@edwardchanjw , It is cool you chimed in. Unlike Caja, the **embed-page** is focusing on microapplication concept, not just embedding but also communication and management over embedded applications. Which makes it distinct from mentioned products.

The Lightning Component Framework looks interesting. So far I got impression you have to use their framework in order to make app. **embed-page** actually meant to be used with any framework in microapplication, solving compatibility between frameworks. The demo with most popular ones is on the todo list yet.

At this stage it is yet proof of concept and I just finishing the unit testing with significant todo list before release.

**Comment by edwardchanjw** [comment]
Thanks for the reply. 
My current knowledge on JavaScript would not be able to fully understand how to implement isolate the JavaScript,
I have an impression that it would be able to reference this [Window vs SecureWindow variable](http://documentation.auraframework.org/lockerApiTest/index.app?aura.mode=DEV) that could be helping for jailing Window and Document variable. I have an assumption they already open source it. Actually i not having knowledge working with SalesForces too, I have an assumption regardless they might require javascript library/app packaging to run on their platform, the secure locker sercice is just based to ES6 Proxy, totally depend entirely on client side. [Locker Service](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/security_ls_unsupported.htm)
